name: Create Development Build
on: [push, workflow_dispatch]
jobs:
  build-publish-image:
    name: Build and Publish Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker Build and Push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ghcr.io/noahburrell0/tnsr-controller:latest,ghcr.io/noahburrell0/tnsr-controller:dev-${{ github.sha }}
